compute: controller-0
oam_if: enp2s1
mgmt_if: enp2s2
physnet0: physnet0
data_net_type: vlan
data_if: eth1000
ceph_osd_disk: sdb
nova_local_disk: sda
nova_size: 40
mgmt_gateway: 192.168.101.1
central_mgmt_address: 192.168.4.0
central_mgmt_prefix: 24